import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';

// Shared, race-safe sequential Code generator — reuses the existing LegacyCodeSequence table
// (Entity, Prefix, LastSeq), the same one account.service.ts's own nextSeq()/generateCode()
// already established (confirmed live in the DB: PK on (Entity, Prefix), already holding
// FI_Account's own C/CS/S sequences). Extracted here — not copy-pasted per entity — because
// this pass adds the identical need to four more entities at once (Warehouse, Unit Set, Size,
// Customer Define Trim); account.service.ts itself is left untouched, still calling its own
// inline copy, since changing already-working code is out of scope here.
//
// An atomic INSERT ... ON CONFLICT DO UPDATE ... RETURNING is one row-level-locked statement,
// so two concurrent callers can never observe/return the same LastSeq. The first time a given
// (entity, prefix) pair is used, the seed comes from the highest existing "{prefix}-NNN" code
// already in the live table — every call after that increments the persisted counter itself,
// never re-deriving from the live table again, so a deleted record's code is never reissued.
export async function nextLegacySeqCode(
  prisma: PrismaService,
  entity: string,
  prefix: string,
  table: string,
  column: string,
  pad = 3,
): Promise<string> {
  const tableRef = Prisma.raw(`"${table}"`);
  const columnRef = Prisma.raw(`"${column}"`);
  const rows = await prisma.$queryRaw<{ LastSeq: number }[]>(Prisma.sql`
    INSERT INTO "LegacyCodeSequence" ("Entity", "Prefix", "LastSeq", "UpdatedAt")
    VALUES (
      ${entity}, ${prefix},
      COALESCE((
        SELECT MAX((regexp_match(${columnRef}, '^' || ${prefix} || '-(\d+)$'))[1]::int)
        FROM ${tableRef} WHERE ${columnRef} LIKE ${prefix + '-%'}
      ), 0) + 1,
      now()
    )
    ON CONFLICT ("Entity", "Prefix") DO UPDATE SET "LastSeq" = "LegacyCodeSequence"."LastSeq" + 1, "UpdatedAt" = now()
    RETURNING "LastSeq"
  `);
  return `${prefix}-${String(rows[0].LastSeq).padStart(pad, '0')}`;
}

// Preview only, for the Create form to display before Save — does NOT consume a sequence slot
// (a plain SELECT, not the atomic INSERT above), so opening the form twice or leaving it idle
// never burns numbers. The authoritative code is always (re)generated by nextLegacySeqCode at
// create() time, which is what actually guarantees uniqueness under concurrency.
export async function previewLegacySeqCode(
  prisma: PrismaService,
  entity: string,
  prefix: string,
  table: string,
  column: string,
  pad = 3,
): Promise<string> {
  const tableRef = Prisma.raw(`"${table}"`);
  const columnRef = Prisma.raw(`"${column}"`);
  const rows = await prisma.$queryRaw<{ LastSeq: number }[]>(Prisma.sql`
    SELECT COALESCE(
      (SELECT "LastSeq" FROM "LegacyCodeSequence" WHERE "Entity" = ${entity} AND "Prefix" = ${prefix}),
      (SELECT MAX((regexp_match(${columnRef}, '^' || ${prefix} || '-(\d+)$'))[1]::int)
       FROM ${tableRef} WHERE ${columnRef} LIKE ${prefix + '-%'}),
      0
    ) as "LastSeq"
  `);
  const next = (rows[0]?.LastSeq ?? 0) + 1;
  return `${prefix}-${String(next).padStart(pad, '0')}`;
}
